# Generated by Django 4.2.1 on 2023-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='MenuItem',
        ),
    ]
